#!/usr/bin/env bash
# Script that transfer a file from our client to a server


usage() {
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
}

if [ "$#" -ne 4 ]; then
	usage
	exit 1
fi

PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP:~/"

if [ $? ]; then
	echo "File transfer successful."
else
	echo "File transfer failed."
fi
