#!/usr/bin/env bash
# Install nginx

apt-get update -y
apt-get install nginx -y

echo "Hello World" | sudo tee /var/www/html/index.html

service nginx start

update-rc.d nginx defaults

service nginx restart

ufw allow 'Nginx HTTP'

curl localhost
