#!/usr/bin/env bash
# configure nginx so that its HTTP response contains a custom header

sudo apt-get update
sudo apt-get install -y nginx


sudo bash -c 'echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		add_header X-Served-By \$hostname;
		try_files \$uri \$uri/ =404;
	}
}" > /etc/nginx/sites-available/default'

sudo service nginx restart
