#!/usr/bin/env bash
# Displays `Best School` 10 times but for the 9th iteration...
# displays Best School and then Hi

num=1

while [ $num -le 10 ]
do
	echo Best School

	if [ $num == 9 ] # checks for the 9th iteration and prints `Hi`
	then
		echo Hi
	fi
	num=$((num + 1))
done
