#!/usr/bin/env bash
# A bash script that loops from 1-10

num=1

while [ $num -le 10 ]
do
	if [ $num == 4 ] # displays bad luck for 4
	then
		echo bad luck
	elif [ $num == 8 ] # displays good luck for 8
	then
		echo good luck
	else
		echo Best School # displays Best School for the rest
	fi
	num=$((num + 1))
done
